<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LGSA4B8" ignored="0" name="Test" tests="8" failures="2" timestamp="2022-06-08T18:04:22 IST" time="0.149" errors="0">
  <testcase name="SecondTest" time="0.017" classname="Analyzer.MyTest">
    <skipped/>
  </testcase> <!-- SecondTest -->
  <testcase name="SecondTest" time="0.003" classname="Analyzer.MyTest">
    <skipped/>
  </testcase> <!-- SecondTest -->
  <testcase name="SecondTest" time="0.003" classname="Analyzer.MyTest">
    <skipped/>
  </testcase> <!-- SecondTest -->
  <testcase name="SecondTest" time="0.002" classname="Analyzer.MyTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Analyzer.MyTest.SecondTest(MyTest.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- SecondTest -->
  <testcase name="firstTest" time="0.002" classname="Analyzer.MyTest">
    <skipped/>
  </testcase> <!-- firstTest -->
  <testcase name="firstTest" time="0.002" classname="Analyzer.MyTest">
    <skipped/>
  </testcase> <!-- firstTest -->
  <testcase name="firstTest" time="0.002" classname="Analyzer.MyTest">
    <skipped/>
  </testcase> <!-- firstTest -->
  <testcase name="firstTest" time="0.003" classname="Analyzer.MyTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Analyzer.MyTest.firstTest(MyTest.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- firstTest -->
</testsuite> <!-- Test -->
